### ISSUE TITLE
无法捕获多层嵌套文件夹中的文件

### ISSUE THREAD

**Issue by 757134** [Hny0305Lin/321Pan_Share_Resolver#2]
![image](https://github.com/user-attachments/assets/203e6a2a-ff88-4dea-bc08-f8552846729f)
如图，红框中所选仍然是文件夹，但无法查看其子文件进而获取下载链接。
另外能否增设文件夹整体下载功能？

**Comment by Hny0305Lin** [comment]
1. 多层嵌套问题今天修复
2. 我会做一个支持，如果勾选了一个文件夹所有文件，则输出的下载链接，会是一个打包了的对话框。

**Comment by Hny0305Lin** [comment]
[目前已经修复，您可以本地部署检查一下](https://github.com/Hny0305Lin/321Pan_Share_Resolver/commit/2f0f7e5eb8cb6df7e5ad0beb1307b879e3baa609)
本Issue将会关闭，如有其他问题，请重新提问。
